// Fetches the Frankly Speaking PODCAST feed into src/data/podcast.json.
//
// The show is hosted on Buzzsprout (show 2643016) and syndicated to Apple /
// Spotify / everywhere from that one RSS feed. This script is the audio twin of
// fetch-playlist.mjs: it turns the feed into a static JSON the app imports, so
// the browser never has to fetch RSS (which is CORS-blocked) and the site works
// on a plain static host.
//
// Episodes come back NEWEST-FIRST — the feed is already in that order, but we
// sort defensively by episode number, then date, in case Buzzsprout reorders.
//
// Re-run whenever Frank publishes:  node scripts/fetch-podcast.mjs
// (The "Update playlist" GitHub Action runs this every 10 minutes and commits
// the file only when something actually changed.)
import { writeFileSync, mkdirSync, readFileSync } from 'node:fs'
import { fileURLToPath } from 'node:url'
import { execFileSync } from 'node:child_process'

const SHOW_ID = '2643016'
const FEED_URL = `https://rss.buzzsprout.com/${SHOW_ID}.rss`

/* ------------------------------- tiny XML ------------------------------- */
// The feed is small and machine-generated by Buzzsprout, so regex parsing is
// safe here and keeps the script dependency-free (same call as fetch-playlist).

const ENTITIES = {
  amp: '&', lt: '<', gt: '>', quot: '"', apos: "'", nbsp: ' ', '#39': "'", '#34': '"',
}

function decode(s) {
  return s
    .replace(/&#(\d+);/g, (_, d) => String.fromCharCode(Number(d)))
    .replace(/&#x([0-9a-f]+);/gi, (_, h) => String.fromCharCode(parseInt(h, 16)))
    .replace(/&([a-z]+|#\d+);/gi, (m, name) => ENTITIES[name.toLowerCase()] ?? m)
}

// Reads <tag>…</tag>, unwrapping CDATA. Returns '' when the tag is absent.
function tag(xml, name) {
  const m = new RegExp(`<${name}(?:\\s[^>]*)?>([\\s\\S]*?)</${name}>`).exec(xml)
  if (!m) return ''
  const raw = m[1].trim()
  const cdata = /^<!\[CDATA\[([\s\S]*)\]\]>$/.exec(raw)
  return (cdata ? cdata[1] : raw).trim()
}

// Reads an attribute off a self-closing tag, e.g. <enclosure url="…" />
function attr(xml, name, key) {
  const m = new RegExp(`<${name}\\b[^>]*\\b${key}="([^"]*)"`).exec(xml)
  return m ? decode(m[1]) : ''
}

// Show-notes HTML → array of plain-text paragraphs (rendered as real <p>s in
// React, so nothing from the feed is ever injected as markup).
function paragraphs(html) {
  if (!html) return []
  return decode(html)
    .replace(/<br\s*\/?>\s*<br\s*\/?>/gi, '\n\n')
    .replace(/<\/p>/gi, '\n\n')
    .replace(/<br\s*\/?>/gi, '\n')
    .replace(/<[^>]+>/g, '')
    .split(/\n{2,}/)
    .map((p) => p.replace(/[ \t]+/g, ' ').trim())
    .filter(Boolean)
}

// "The Israel–Iran War, Part 1 | Frankly Speaking" → "The Israel–Iran War, Part 1"
function cleanTitle(t) {
  return t
    .replace(/\s*\|\s*Frankly\s*Speaking(\s*Podcast)?\s*$/i, '')
    .replace(/\s*[–—-]\s*Frankly\s*Speaking(\s*Podcast)?\s*$/i, '')
    .trim()
}

/* ------------------------------- waveform ------------------------------- */
/* REAL peak data, not a decorative squiggle: ffmpeg decodes the published MP3
   to low-rate mono PCM and we take the RMS of each bucket.

   One honest caveat, worth knowing before anyone reads meaning into the shape:
   these episodes are loudness-normalised to about -16 LUFS, so raw RMS across
   ~25-second buckets sits in a narrow band (measured 62-100 on episode 1) and
   would draw as an almost flat block. The values below are therefore CONTRAST-
   STRETCHED — the 5th-95th percentile is mapped to 18-100, the same idea as
   pulling levels on a photograph. The variation is real and in the right place;
   only its amplitude is exaggerated so the eye can read it.

   Peaks are cached per episode in podcast.json, so the 10-minute Action only
   ever pays the download+decode cost for genuinely new episodes. If ffmpeg is
   missing or anything fails, peaks come back null and the player falls back to
   a plain progress bar. */
const BUCKETS = 160

function hasFfmpeg() {
  try {
    execFileSync('ffmpeg', ['-version'], { stdio: 'ignore' })
    return true
  } catch {
    return false
  }
}

function peaksFor(url) {
  let pcm
  try {
    // ffmpeg reads the URL directly — no 50MB temp file. The UA matters:
    // Buzzsprout's CDN refuses requests that don't look like a browser.
    pcm = execFileSync(
      'ffmpeg',
      ['-v', 'error', '-user_agent', 'Mozilla/5.0', '-i', url,
       '-ac', '1', '-ar', '4000', '-f', 's16le', '-'],
      { maxBuffer: 1024 * 1024 * 512, timeout: 600_000 }
    )
  } catch (err) {
    console.warn('  [warn] could not decode audio for peaks: ' + String(err.message).slice(0, 140))
    return null
  }

  const n = Math.floor(pcm.length / 2)
  if (n < BUCKETS * 4) return null
  const size = Math.floor(n / BUCKETS)

  const rms = []
  for (let b = 0; b < BUCKETS; b++) {
    let sum = 0
    const start = b * size
    for (let i = 0; i < size; i++) {
      const v = pcm.readInt16LE((start + i) * 2)
      sum += v * v
    }
    rms.push(Math.sqrt(sum / size))
  }

  // contrast stretch: p5..p95 -> 0.18..1
  const sorted = [...rms].sort((a, b) => a - b)
  const lo = sorted[Math.floor(sorted.length * 0.05)]
  const hi = Math.max(sorted[Math.floor(sorted.length * 0.95)], lo + 1)
  return rms.map((v) => {
    const t = Math.min(1, Math.max(0, (v - lo) / (hi - lo)))
    return Math.round((0.18 + 0.82 * t) * 100)
  })
}

/* -------------------------------- fetch -------------------------------- */

console.log(`Fetching podcast feed: ${FEED_URL}`)
const res = await fetch(FEED_URL, {
  headers: { 'user-agent': 'frankly-speaking-site/1.0 (+https://franklyspeakingshow.com)' },
})
if (!res.ok) {
  console.error(`✖ Feed request failed: ${res.status} ${res.statusText}`)
  process.exit(1)
}
const xml = await res.text()

const head = xml.slice(0, xml.indexOf('<item>') === -1 ? undefined : xml.indexOf('<item>'))

const show = {
  title: decode(tag(head, 'title')) || 'Frankly Speaking Podcast',
  author: decode(tag(head, 'itunes:author')),
  email: decode(tag(head, 'itunes:email')),
  image: attr(head, 'itunes:image', 'href'),
  feedUrl: FEED_URL,
  showId: SHOW_ID,
  paragraphs: paragraphs(tag(head, 'description')),
}

const items = xml.match(/<item>[\s\S]*?<\/item>/g) || []

const episodes = items
  .map((it) => {
    const guid = tag(it, 'guid')
    const id = (/Buzzsprout-(\d+)/.exec(guid) || [])[1] || guid
    const audio = attr(it, 'enclosure', 'url')
    const rawTitle = decode(tag(it, 'itunes:title') || tag(it, 'title'))
    const pub = tag(it, 'pubDate')
    const ts = pub ? Date.parse(pub) : NaN
    const notes = paragraphs(tag(it, 'content:encoded') || tag(it, 'description'))
    const num = Number(tag(it, 'itunes:episode')) || null

    return {
      id,
      num,
      title: cleanTitle(rawTitle).normalize('NFC'),
      // First paragraph = the one-line pitch used on cards; the rest is detail.
      summary: notes[0] || '',
      notes,
      audio,
      // Buzzsprout's public episode page (also where the "…mp3" URL points).
      pageUrl: audio ? audio.replace(/\.mp3(\?.*)?$/, '') : '',
      image: attr(it, 'itunes:image', 'href') || show.image,
      duration: Number(tag(it, 'itunes:duration')) || null, // seconds
      date: Number.isNaN(ts) ? null : new Date(ts).toISOString().slice(0, 10),
      size: Number(attr(it, 'enclosure', 'length')) || null,
    }
  })
  .filter((e) => e.id && e.audio)

// Newest first: highest episode number wins; undated/unnumbered keep feed order.
episodes.sort((a, b) => {
  if (a.num != null && b.num != null && a.num !== b.num) return b.num - a.num
  if (a.date && b.date && a.date !== b.date) return a.date < b.date ? 1 : -1
  return 0
})

// Peaks already computed by a previous run — never recompute these.
const cachedPeaks = new Map()
const outDirEarly = fileURLToPath(new URL('../src/data/', import.meta.url))
try {
  const prev = JSON.parse(readFileSync(outDirEarly + 'podcast.json', 'utf8'))
  for (const e of prev.episodes || []) if (e.id && e.peaks) cachedPeaks.set(e.id, e.peaks)
} catch {
  /* first run — nothing cached yet */
}

const ffmpegAvailable = hasFfmpeg()
if (!ffmpegAvailable) console.warn('⚠ ffmpeg not found — shipping episodes without waveform peaks')

for (const ep of episodes) {
  if (cachedPeaks.has(ep.id)) {
    ep.peaks = cachedPeaks.get(ep.id)
    continue
  }
  if (!ffmpegAvailable) {
    ep.peaks = null
    continue
  }
  console.log(`Analysing waveform for “${ep.title}”…`)
  ep.peaks = peaksFor(ep.audio)
}

const outDir = fileURLToPath(new URL('../src/data/', import.meta.url))
mkdirSync(outDir, { recursive: true })
writeFileSync(
  outDir + 'podcast.json',
  JSON.stringify({ show, count: episodes.length, episodes }, null, 2) + '\n'
)

console.log(
  `Wrote ${episodes.length} episode(s) to src/data/podcast.json` +
    (episodes[0] ? ` (newest: ${episodes[0].title})` : '')
)
